conf.py:
  project: Different HTTP statuscodes for shortcuts
  version: 1.0.0
  release: 1.0.0
  latex_documents:
  - - Index
    - shortcut_statuscodes.tex
    - Different HTTP statuscodes for shortcuts
    - Dan Untenzu
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
